name: Freeze PR dependency changes

on:
  pull_request:
    branches:
      - master
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  freeze-pr-dep-changes:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    uses: FasterSpeeding/Piped/.github/workflows/freeze-for-pr.yml@fdc7f1d4ae22dc6423d55585f3d1f1ec596d6e6d
    secrets: inherit
