name: Freeze PR dependency changes

on:
  pull_request:
    branches:
      - master
    paths: ["piped", "pyproject.toml"]

jobs:
  freeze-pr-dep-changes:
    uses: FasterSpeeding/Piped/.github/workflows/freeze-for-pr.yml@66d53e2dfe7a90bdac76106bc79c4a02aecd0446
    secrets: inherit
