name: Lint Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  actionlint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@12f12b2c1f7aef76182a0337ae9c577661cf6aae
    with:
      sessions: "verify-markup spell-check lint slot-check"
