name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@d19d7341ef655ff54d8c6f7bcd92c544872944a5
    with:
      sessions: "verify-markup spell-check lint slot-check"
