name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@f824d61c518eb6a04b59e6b02980e5ce0fd80a50
    with:
      sessions: "verify-markup spell-check lint slot-check"
