name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@fdc7f1d4ae22dc6423d55585f3d1f1ec596d6e6d
    with:
      sessions: "verify-markup spell-check lint slot-check"
