name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@2d96ccdfe342b4b489f6ff753ef3ecb49629fade
    with:
      sessions: "verify-markup spell-check lint slot-check"
