name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@1ccc9c614a20fe0ec6c39c4de0b456b183dc386c
    with:
      sessions: "verify-markup spell-check lint slot-check"
