name: Lint Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  actionlint:
    uses: FasterSpeeding/Piped/.github/workflows/lint-actions.yml@fdc7f1d4ae22dc6423d55585f3d1f1ec596d6e6d
