name: Deploy PR preview docs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-docs-preview:
    permissions:
      contents: write
      pull-requests: write

    uses: FasterSpeeding/Piped/.github/workflows/pr-docs.yml@adc711961a6c2e5eb5b6c6389103b736356dc8e6
    secrets: inherit
