name: Deploy PR preview docs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-docs-preview:
    permissions:
      contents: write
      pull-requests: write

    uses: FasterSpeeding/Piped/.github/workflows/pr-docs.yml@bbf25404cc7d40823c6de466c12b6ecdb53629c8
    secrets: inherit
    with:
      sessions: "verify-markup spell-check lint slot-check"
