name: Deploy PR preview docs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-docs-preview:
    permissions:
      contents: write
      pull-requests: write

    uses: FasterSpeeding/Piped/.github/workflows/pr-docs.yml@7f5789a5b500b5ea084370b88f9ff7716de03d65
    secrets: inherit
