name: Deploy PR preview docs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-docs-preview:
    permissions:
      contents: write
      pull-requests: write

    uses: FasterSpeeding/Piped/.github/workflows/pr-docs.yml@12f12b2c1f7aef76182a0337ae9c577661cf6aae
    secrets: inherit
