name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    permissions:
      id-token: write

    uses: FasterSpeeding/Piped/.github/workflows/py-test.yml@076d0e3ac85d243cb9ca2123b1144364ce7f8a4b
    secrets: inherit
    with:
      os-versions: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      python-versions: '["3.11", "3.12", "3.13", "3.14-dev"]'
