name: Run tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  py-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14-dev"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: nox -s test-coverage

      - name: Create coverage artifacts
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: .coverage.${{ matrix.os }}.${{ matrix.python-version }}
          path: artifacts/.coverage
          include-hidden-files: true
          if-no-files-found: error

  upload-coverage:
    needs: [py-test]
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          pattern: .coverage.*
          merge-multiple: false
          path: ./artifacts/coverage/
          recurse_submodules: true

      - name: Combine coverage artifacts
        run: nox -s combine-coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          directory: ./artifacts/coverage/
