name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    uses: FasterSpeeding/Piped/.github/workflows/py-test.yml@bbf25404cc7d40823c6de466c12b6ecdb53629c8
    secrets: inherit
    with:
      os-versions: '["ubuntu-latest", "macos-latest", "windows-latest]'
      python-versions: '["3.11", "3.12", "3.13", "3.14-dev"]'
