name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    permissions:
      id-token: write

    uses: FasterSpeeding/Piped/.github/workflows/py-test.yml@25d4c5b8d7cf42764b3a978de34cad31bbe53323
    secrets: inherit
    with:
      os-versions: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      python-versions: '["3.11", "3.12", "3.13", "3.14-dev"]'
