name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    permissions:
      id-token: write

    uses: FasterSpeeding/Piped/.github/workflows/py-test.yml@f824d61c518eb6a04b59e6b02980e5ce0fd80a50
    secrets: inherit
    with:
      os-versions: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      python-versions: '["3.11", "3.12", "3.13", "3.14-dev"]'
