name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@076d0e3ac85d243cb9ca2123b1144364ce7f8a4b
    secrets: inherit
