name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@f824d61c518eb6a04b59e6b02980e5ce0fd80a50
    secrets: inherit
