name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@d19d7341ef655ff54d8c6f7bcd92c544872944a5
    secrets: inherit
