name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@fdc7f1d4ae22dc6423d55585f3d1f1ec596d6e6d
    secrets: inherit
