name: Publish documentation

on:
  workflow_call:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types:
      - published

jobs:
  publish-docs:
    uses: FasterSpeeding/Piped/.github/workflows/release-docs.yml@adc711961a6c2e5eb5b6c6389103b736356dc8e6
    secrets: inherit
