name: Publish documentation

on:
  workflow_call:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types:
      - published

jobs:
  publish-docs:
    uses: FasterSpeeding/Piped/.github/workflows/release-docs.yml@d19d7341ef655ff54d8c6f7bcd92c544872944a5
    secrets: inherit
