name: Type check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  type-check:
    uses: FasterSpeeding/Piped/.github/workflows/type-check.yml@030a614a47058aded1fc89ab1c28ccd4259a5ce7
