name: Update licence

on:
  schedule:
    - cron: "0 7 1 1 *"
  workflow_dispatch:

jobs:
  update-licence:
    uses: FasterSpeeding/Piped/.github/workflows/update-licence.yml@076d0e3ac85d243cb9ca2123b1144364ce7f8a4b
    secrets: inherit
