name: Verify type-completeness

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  verify-types:
    uses: FasterSpeeding/Piped/.github/workflows/verify-types.yml@66d53e2dfe7a90bdac76106bc79c4a02aecd0446
