name: Verify type-completeness

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  verify-types:
    uses: FasterSpeeding/Piped/.github/workflows/verify-types.yml@adc711961a6c2e5eb5b6c6389103b736356dc8e6
